# Generated by Django 6.0.1 on 2026-01-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('celular', models.CharField(max_length=15)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('documento', models.CharField(blank=True, max_length=45, null=True)),
                ('nascimento', models.DateField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('profissao', models.CharField(blank=True, max_length=45, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=80, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=45, null=True)),
                ('bairro', models.CharField(blank=True, max_length=45, null=True)),
                ('cidade', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('mae', models.CharField(blank=True, max_length=80, null=True)),
                ('pai', models.CharField(blank=True, max_length=80, null=True)),
                ('cod_convenio', models.IntegerField(blank=True, null=True)),
                ('carteira_conv', models.CharField(blank=True, max_length=25, null=True)),
                ('obs', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('uscad', models.CharField(blank=True, max_length=25, null=True)),
                ('dtcad', models.DateTimeField(auto_now_add=True)),
                ('usalt', models.CharField(blank=True, max_length=25, null=True)),
                ('dtalt', models.DateTimeField(auto_now=True)),
                ('sus', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('carteira_sus', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
