# Generated by Django 6.0.1 on 2026-02-04 19:14

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPaciente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cpf', models.CharField(db_index=True, max_length=15)),
                ('nome', models.CharField(max_length=80)),
                ('celular', models.CharField(max_length=15)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('documento', models.CharField(blank=True, max_length=45, null=True)),
                ('nascimento', models.DateField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('profissao', models.CharField(blank=True, max_length=45, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=80, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=45, null=True)),
                ('bairro', models.CharField(blank=True, max_length=45, null=True)),
                ('cidade', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('mae', models.CharField(blank=True, max_length=80, null=True)),
                ('pai', models.CharField(blank=True, max_length=80, null=True)),
                ('cod_convenio', models.IntegerField(blank=True, null=True)),
                ('carteira_conv', models.CharField(blank=True, max_length=25, null=True)),
                ('obs', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('uscad', models.CharField(blank=True, max_length=25, null=True)),
                ('dtcad', models.DateTimeField(blank=True, editable=False)),
                ('usalt', models.CharField(blank=True, max_length=25, null=True)),
                ('dtalt', models.DateTimeField(blank=True, editable=False)),
                ('sus', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('carteira_sus', models.CharField(blank=True, max_length=45, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical paciente',
                'verbose_name_plural': 'historical pacientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
