# Generated by Django 6.0.1 on 2026-02-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_historicalpaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaciente',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='sus',
            field=models.BooleanField(default=False, verbose_name='Possui SUS'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sus',
            field=models.BooleanField(default=False, verbose_name='Possui SUS'),
        ),
    ]
