# Generated by Django 6.0.1 on 2026-02-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_alter_historicalpaciente_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaciente',
            name='sus',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sus',
        ),
    ]
