# Generated by Django 6.0.1 on 2026-02-09 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('paciente', '0004_remove_historicalpaciente_sus_remove_paciente_sus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaciente',
            name='cod_convenio',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cod_convenio',
        ),
        migrations.AddField(
            model_name='historicalpaciente',
            name='convenio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.convenio', verbose_name='Convênio'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.convenio', verbose_name='Convênio'),
        ),
    ]
