# Generated by Django 6.0.1 on 2026-03-04 00:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_statusagendamento_statusautorizacao_and_more'),
        ('paciente', '0006_alter_historicalpaciente_convenio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPacienteVacina',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_aplicacao', models.DateField(blank=True, null=True)),
                ('descricao_vacina', models.CharField(blank=True, max_length=100, null=True)),
                ('obs', models.CharField(blank=True, max_length=1000, null=True)),
                ('uscad', models.CharField(blank=True, max_length=25, null=True)),
                ('dtcad', models.DateTimeField(blank=True, editable=False)),
                ('usalt', models.CharField(blank=True, max_length=25, null=True)),
                ('dtalt', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aplicador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aplicador')),
                ('forma_pagamento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.formapagamento', verbose_name='Forma de Pagamento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='paciente.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'historical Vacina do Paciente',
                'verbose_name_plural': 'historical Vacinas do Paciente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PacienteVacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField(blank=True, null=True)),
                ('descricao_vacina', models.CharField(blank=True, max_length=100, null=True)),
                ('obs', models.CharField(blank=True, max_length=1000, null=True)),
                ('uscad', models.CharField(blank=True, max_length=25, null=True)),
                ('dtcad', models.DateTimeField(auto_now_add=True)),
                ('usalt', models.CharField(blank=True, max_length=25, null=True)),
                ('dtalt', models.DateTimeField(auto_now=True)),
                ('aplicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacinas_aplicadas', to=settings.AUTH_USER_MODEL, verbose_name='Aplicador')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.formapagamento', verbose_name='Forma de Pagamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='paciente.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Vacina do Paciente',
                'verbose_name_plural': 'Vacinas do Paciente',
            },
        ),
    ]
