# Generated by Django 6.0.1 on 2026-03-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_historicalpacientevacina_pacientevacina'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpacientevacina',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='pacientevacina',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
