# Generated by Django 6.0.1 on 2026-04-18 01:08

import django.db.models.deletion
from django.db import migrations, models


def vincular_pacientes_a_clinica(apps, schema_editor):
    Clinica = apps.get_model('usuario', 'Clinica')
    Paciente = apps.get_model('paciente', 'Paciente')
    PacienteVacina = apps.get_model('paciente', 'PacienteVacina')
    HistoricalPaciente = apps.get_model('paciente', 'HistoricalPaciente')
    HistoricalPacienteVacina = apps.get_model('paciente', 'HistoricalPacienteVacina')

    clinica = Clinica.objects.order_by('id').first()
    if not clinica:
        return

    Paciente.objects.filter(clinica__isnull=True).update(clinica=clinica)
    for vacina in PacienteVacina.objects.select_related('paciente').all():
        vacina.clinica = vacina.paciente.clinica if vacina.paciente_id and vacina.paciente and vacina.paciente.clinica_id else clinica
        vacina.save(update_fields=['clinica'])

    HistoricalPaciente.objects.filter(clinica__isnull=True).update(clinica=clinica)
    HistoricalPacienteVacina.objects.filter(clinica__isnull=True).update(clinica=clinica)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_convenio_clinica_especialidade_clinica_and_more'),
        ('paciente', '0008_historicalpacientevacina_valor_pacientevacina_valor'),
        ('usuario', '0010_clinica_historicalunidade_clinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaciente',
            name='clinica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='historicalpacientevacina',
            name='clinica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='pacientevacina',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paciente_vacinas', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='cpf',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=15),
        ),
        migrations.RunPython(vincular_pacientes_a_clinica, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('clinica', 'cpf'), name='paciente_unique_cpf_por_clinica'),
        ),
    ]
