# Generated by Django 6.0.1 on 2026-04-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_historicalpaciente_clinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaciente',
            name='prontuario',
            field=models.TextField(blank=True, verbose_name='Prontuário'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='prontuario',
            field=models.TextField(blank=True, verbose_name='Prontuário'),
        ),
    ]
