# Generated by Django 6.0.1 on 2026-03-16 13:35

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_statusagendamento_statusautorizacao_and_more'),
        ('medico', '0004_remove_historicalmedicoespecialidade_dtalt_and_more'),
        ('paciente', '0006_alter_historicalpaciente_convenio_and_more'),
        ('usuario', '0009_alter_historicalusuario_cod_medico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAgenda',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('A', 'Agendado'), ('B', 'Bloqueado')], default='D', max_length=1, verbose_name='Status do Horário')),
                ('uscad', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Cadastro')),
                ('dtcad', models.DateTimeField(blank=True, editable=False, verbose_name='Data Cadastro')),
                ('usalt', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Alteração')),
                ('dtalt', models.DateTimeField(blank=True, editable=False, verbose_name='Data Alteração')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('convenio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.convenio', verbose_name='Convênio')),
                ('especialidade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.especialidade', verbose_name='Especialidade')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='medico.medico', verbose_name='Médico')),
                ('paciente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='paciente.paciente', verbose_name='Paciente')),
                ('status_agendamento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.statusagendamento', verbose_name='Status do Agendamento')),
                ('tipo_consulta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.tipoconsulta', verbose_name='Tipo de Consulta')),
                ('unidade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'historical Agenda de Consulta',
                'verbose_name_plural': 'historical Agendas de Consultas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('A', 'Agendado'), ('B', 'Bloqueado')], default='D', max_length=1, verbose_name='Status do Horário')),
                ('uscad', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Cadastro')),
                ('dtcad', models.DateTimeField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('usalt', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Alteração')),
                ('dtalt', models.DateTimeField(auto_now=True, verbose_name='Data Alteração')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.convenio', verbose_name='Convênio')),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.especialidade', verbose_name='Especialidade')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_agenda', to='medico.medico', verbose_name='Médico')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='paciente.paciente', verbose_name='Paciente')),
                ('status_agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.statusagendamento', verbose_name='Status do Agendamento')),
                ('tipo_consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tipoconsulta', verbose_name='Tipo de Consulta')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Agenda de Consulta',
                'verbose_name_plural': 'Agendas de Consultas',
                'db_table': 'agenda',
                'ordering': ['data', 'hora'],
                'constraints': [models.UniqueConstraint(fields=('data', 'hora', 'medico', 'unidade'), name='agenda_unique_horario_medico_unidade')],
            },
        ),
    ]
