# Generated by Django 6.0.1 on 2026-04-18 01:08

import django.db.models.deletion
from django.db import migrations, models


def vincular_agendas_a_clinica(apps, schema_editor):
    Clinica = apps.get_model('usuario', 'Clinica')
    Agenda = apps.get_model('agenda', 'Agenda')
    HistoricalAgenda = apps.get_model('agenda', 'HistoricalAgenda')

    clinica = Clinica.objects.order_by('id').first()
    if not clinica:
        return

    for agenda in Agenda.objects.select_related('unidade', 'medico').all():
        clinica_agenda = None
        if agenda.unidade_id and agenda.unidade and agenda.unidade.clinica_id:
            clinica_agenda = agenda.unidade.clinica
        elif agenda.medico_id and agenda.medico and agenda.medico.clinica_id:
            clinica_agenda = agenda.medico.clinica
        agenda.clinica = clinica_agenda or clinica
        agenda.save(update_fields=['clinica'])

    HistoricalAgenda.objects.filter(clinica__isnull=True).update(clinica=clinica)


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('usuario', '0010_clinica_historicalunidade_clinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendas_consulta', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='historicalagenda',
            name='clinica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.RunPython(vincular_agendas_a_clinica, migrations.RunPython.noop),
    ]
