# Generated by Django 6.0.1 on 2026-04-22 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agenda_clinica_historicalagenda_clinica'),
        ('base', '0005_convenio_clinica_especialidade_clinica_and_more'),
        ('medico', '0006_alter_medicoagenda_options_and_more'),
        ('paciente', '0009_historicalpaciente_clinica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agenda',
            name='agenda_unique_horario_medico_unidade',
        ),
        migrations.RemoveField(
            model_name='historicalagenda',
            name='unidade',
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(fields=('data', 'hora', 'medico'), name='agenda_unique_horario_medico'),
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='unidade',
        ),
    ]
