# Generated by Django 6.0.1 on 2026-04-22 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_remove_agenda_agenda_unique_horario_medico_unidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='historicalagenda',
            name='clinica',
        ),
    ]
