# Generated by Django 6.0.1 on 2026-02-23 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
        ('usuario', '0008_historicalunidade_historicalusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmedico',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='historicalmedico',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='historicalmedico',
            name='unidade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.unidade', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='medico',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='medico',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.unidade', verbose_name='Unidade'),
        ),
    ]
