# Generated by Django 6.0.1 on 2026-03-01 20:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_statusagendamento_statusautorizacao_and_more'),
        ('medico', '0002_remove_historicalmedico_especialidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMedicoEspecialidade',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=100, verbose_name='Descrição/Observação')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('uscad', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Cadastro')),
                ('dtcad', models.DateTimeField(blank=True, editable=False, verbose_name='Data Cadastro')),
                ('usalt', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Alteração')),
                ('dtalt', models.DateTimeField(blank=True, editable=False, verbose_name='Data Alteração')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('especialidade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.especialidade', verbose_name='Especialidade')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='medico.medico', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'historical Médico Especialidade',
                'verbose_name_plural': 'historical Médicos Especialidades',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MedicoEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=100, verbose_name='Descrição/Observação')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('uscad', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Cadastro')),
                ('dtcad', models.DateTimeField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('usalt', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Alteração')),
                ('dtalt', models.DateTimeField(auto_now=True, verbose_name='Data Alteração')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.especialidade', verbose_name='Especialidade')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='medico.medico', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Médico Especialidade',
                'verbose_name_plural': 'Médicos Especialidades',
                'db_table': 'medico_especialidade',
                'ordering': ['medico__nome', 'especialidade__descricao'],
                'unique_together': {('medico', 'especialidade')},
            },
        ),
    ]
