# Generated by Django 6.0.1 on 2026-03-01 23:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_historicalmedicoespecialidade_medicoespecialidade'),
        ('usuario', '0008_historicalunidade_historicalusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmedicoespecialidade',
            name='dtalt',
        ),
        migrations.RemoveField(
            model_name='historicalmedicoespecialidade',
            name='usalt',
        ),
        migrations.RemoveField(
            model_name='medicoespecialidade',
            name='dtalt',
        ),
        migrations.RemoveField(
            model_name='medicoespecialidade',
            name='usalt',
        ),
        migrations.CreateModel(
            name='HistoricalMedicoAgenda',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('uscad', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Cadastro')),
                ('dtcad', models.DateTimeField(blank=True, editable=False, verbose_name='Data Cadastro')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='medico.medico', verbose_name='Médico')),
                ('unidade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'historical Médico Agenda',
                'verbose_name_plural': 'historical Médicos Agendas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MedicoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('uscad', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Cadastro')),
                ('dtcad', models.DateTimeField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='medico.medico', verbose_name='Médico')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Médico Agenda',
                'verbose_name_plural': 'Médicos Agendas',
                'db_table': 'medico_agenda',
                'ordering': ['medico__nome', 'unidade__descricao', 'hora'],
            },
        ),
    ]
