# Generated by Django 6.0.1 on 2026-04-18 01:08

import django.db.models.deletion
from django.db import migrations, models


def vincular_medicos_a_clinica(apps, schema_editor):
    Clinica = apps.get_model('usuario', 'Clinica')
    Medico = apps.get_model('medico', 'Medico')
    MedicoAgenda = apps.get_model('medico', 'MedicoAgenda')
    MedicoEspecialidade = apps.get_model('medico', 'MedicoEspecialidade')
    HistoricalMedico = apps.get_model('medico', 'HistoricalMedico')
    HistoricalMedicoAgenda = apps.get_model('medico', 'HistoricalMedicoAgenda')
    HistoricalMedicoEspecialidade = apps.get_model('medico', 'HistoricalMedicoEspecialidade')

    clinica_padrao = Clinica.objects.order_by('id').first()
    if not clinica_padrao:
        return

    for medico in Medico.objects.select_related('unidade').all():
        clinica = medico.unidade.clinica if medico.unidade_id and medico.unidade and medico.unidade.clinica_id else clinica_padrao
        if not medico.clinica_id:
            medico.clinica = clinica
            medico.save(update_fields=['clinica'])

    for agenda in MedicoAgenda.objects.select_related('medico', 'unidade').all():
        clinica = None
        if agenda.unidade_id and agenda.unidade and agenda.unidade.clinica_id:
            clinica = agenda.unidade.clinica
        elif agenda.medico_id and agenda.medico and agenda.medico.clinica_id:
            clinica = agenda.medico.clinica
        agenda.clinica = clinica or clinica_padrao
        agenda.save(update_fields=['clinica'])

    for vinculo in MedicoEspecialidade.objects.select_related('medico').all():
        vinculo.clinica = vinculo.medico.clinica if vinculo.medico_id and vinculo.medico and vinculo.medico.clinica_id else clinica_padrao
        vinculo.save(update_fields=['clinica'])

    HistoricalMedico.objects.filter(clinica__isnull=True).update(clinica=clinica_padrao)
    HistoricalMedicoAgenda.objects.filter(clinica__isnull=True).update(clinica=clinica_padrao)
    HistoricalMedicoEspecialidade.objects.filter(clinica__isnull=True).update(clinica=clinica_padrao)


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_remove_historicalmedicoespecialidade_dtalt_and_more'),
        ('usuario', '0010_clinica_historicalunidade_clinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmedico',
            name='clinica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='historicalmedicoagenda',
            name='clinica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='historicalmedicoespecialidade',
            name='clinica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='medico',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicos', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='medicoagenda',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medico_agendas', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='medicoespecialidade',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medico_especialidades', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AlterField(
            model_name='historicalmedico',
            name='crm',
            field=models.CharField(max_length=20, verbose_name='CRM'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=20, verbose_name='CRM'),
        ),
        migrations.RunPython(vincular_medicos_a_clinica, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='medico',
            constraint=models.UniqueConstraint(fields=('clinica', 'crm'), name='medico_unique_crm_por_clinica'),
        ),
    ]
