# Generated by Django 6.0.1 on 2026-04-22 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0005_historicalmedico_clinica_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicoagenda',
            options={'ordering': ['medico__nome', 'hora'], 'verbose_name': 'Médico Agenda', 'verbose_name_plural': 'Médicos Agendas'},
        ),
        migrations.RemoveField(
            model_name='historicalmedico',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='historicalmedicoagenda',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='medicoagenda',
            name='unidade',
        ),
    ]
