# Generated by Django 6.0.1 on 2026-02-28 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0006_alter_historicalpaciente_convenio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_autorizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('NEGADA', 'Negada')], default='PENDENTE', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enfermagem.procedimento')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaEnfermagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateTimeField()),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('autorizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enfermagem.autorizacao')),
            ],
        ),
    ]
