# Generated by Django 6.0.1 on 2026-02-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
