# Generated by Django 6.0.1 on 2026-02-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0002_alter_procedimento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
