# Generated by Django 6.0.1 on 2026-03-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0003_alter_procedimento_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
