# Generated by Django 6.0.1 on 2026-03-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enfermagem", "0004_procedimento_nome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="procedimento",
            name="id",
        ),
        migrations.AlterField(
            model_name="procedimento",
            name="codigo",
            field=models.AutoField(
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="procedimento",
            name="descricao",
            field=models.CharField(
                default="", max_length=100, verbose_name="Descrição do Procedimento"
            ),
        ),
        migrations.AlterField(
            model_name="procedimento",
            name="nome",
            field=models.CharField(
                default="", max_length=100, verbose_name="Nome do Procedimento"
            ),
        ),
    ]
