# Generated by Django 6.0.1 on 2026-03-20 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0005_remove_procedimento_id_alter_procedimento_codigo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimento',
            old_name='codigo',
            new_name='id',
        ),
    ]
