# Generated by Django 6.0.1 on 2026-03-22 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0006_rename_codigo_procedimento_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaenfermagem',
            name='hora_agendamento',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
