# Generated by Django 6.0.1 on 2026-03-31 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0007_agendaenfermagem_hora_agendamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enfermeiro',
        ),
        migrations.AlterModelOptions(
            name='agendaenfermagem',
            options={'ordering': ['data_agendamento', 'hora_agendamento']},
        ),
        migrations.RemoveField(
            model_name='autorizacao',
            name='numero_autorizacao',
        ),
    ]
