# Generated by Django 6.0.1 on 2026-04-18 01:08

import django.db.models.deletion
from django.db import migrations, models


def vincular_enfermagem_a_clinica(apps, schema_editor):
    Clinica = apps.get_model('usuario', 'Clinica')
    Procedimento = apps.get_model('enfermagem', 'Procedimento')
    Autorizacao = apps.get_model('enfermagem', 'Autorizacao')
    AgendaEnfermagem = apps.get_model('enfermagem', 'AgendaEnfermagem')

    clinica = Clinica.objects.order_by('id').first()
    if not clinica:
        return

    Procedimento.objects.filter(clinica__isnull=True).update(clinica=clinica)

    for autorizacao in Autorizacao.objects.select_related('paciente').all():
        clinica_autorizacao = autorizacao.paciente.clinica if autorizacao.paciente_id and autorizacao.paciente and autorizacao.paciente.clinica_id else clinica
        autorizacao.clinica = clinica_autorizacao
        autorizacao.save(update_fields=['clinica'])

    for agendamento in AgendaEnfermagem.objects.select_related('autorizacao').all():
        clinica_agendamento = agendamento.autorizacao.clinica if agendamento.autorizacao_id and agendamento.autorizacao and agendamento.autorizacao.clinica_id else clinica
        agendamento.clinica = clinica_agendamento
        agendamento.save(update_fields=['clinica'])


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0008_delete_enfermeiro_alter_agendaenfermagem_options_and_more'),
        ('paciente', '0009_historicalpaciente_clinica_and_more'),
        ('usuario', '0010_clinica_historicalunidade_clinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaenfermagem',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos_enfermagem', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes_enfermagem', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procedimentos_enfermagem', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.RunPython(vincular_enfermagem_a_clinica, migrations.RunPython.noop),
    ]
