# Generated by Django 6.0.1 on 2026-01-26 20:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=80, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=120, null=True, verbose_name='Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('plano', models.CharField(choices=[('BASICO', 'Básico'), ('PROFISSIONAL', 'Profissional')], default='BASICO', max_length=20, verbose_name='Plano')),
                ('status', models.BooleanField(default=True, verbose_name='Ativa')),
                ('uscad', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Cadastro')),
                ('dtcad', models.DateTimeField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('usalt', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Alteração')),
                ('dtalt', models.DateTimeField(auto_now=True, verbose_name='Data Alteração')),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('reseta_senha', models.BooleanField(default=False, verbose_name='Forçar Redefinição de Senha')),
                ('perfil', models.CharField(choices=[('ADMIN', 'Administrador'), ('MEDICO', 'Médico'), ('ENFERMAGEM', 'Enfermagem'), ('RECEPCAO', 'Recepção')], default='RECEPCAO', max_length=20)),
                ('cod_medico', models.IntegerField(blank=True, null=True, verbose_name='Cód. Médico')),
                ('cod_unidade', models.IntegerField(blank=True, null=True, verbose_name='Cód. Unidade')),
                ('obs', models.TextField(blank=True, verbose_name='Observações')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
