# Generated by Django 6.0.1 on 2026-02-02 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_permissao_permissaousuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('pode_ver_botao', 'Pode ver botão especial')]},
        ),
    ]
