# Generated by Django 6.0.1 on 2026-02-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('mnu_pacientes', 'Menu Pacientes'), ('campo_sus', 'Campo Cartão do SUS'), ('tab_medicacoes', 'Guia Medicações'), ('tab_exames', 'Guia Exames'), ('mnu_agconsultas', 'Menu Agenda de Consultas'), ('mnu_agmedico', 'Menu Agenda do Médico'), ('mnu_enfermagem', 'Menu Enfermagem'), ('mnu_autorizacoes', 'Menu Autorizações'), ('mnu_liberacoes', 'Menu Liberações'), ('mnu_atendimento', 'Menu Atendimento'), ('mnu_financeiro', 'Menu Financeiro'), ('mnu_config', 'Menu Configurações'), ('mnu_convenios', 'Menu Convênios'), ('mnu_fpagamento', 'Menu Formas de Pagamento'), ('mnu_tpconsultas', 'Menu Tipos de Consultas'), ('mnu_tpexames', 'Menu Tipos de Exames'), ('mnu_tpmateriais', 'Menu Tipos de Materiais'), ('mnu_materiais', 'Menu Materiais'), ('mnu_espec', 'Menu Especialidades'), ('mnu_cadmedicos', 'Menu Cadastro de Médicos'), ('mnu_unidades', 'Menu Unidades'), ('mnu_cadusuarios', 'Menu Cadastro de Usuários')]},
        ),
    ]
