# Generated by Django 6.0.1 on 2026-02-03 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45, verbose_name='Descrição')),
                ('status', models.CharField(blank=True, max_length=1, null=True, verbose_name='Status')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=45, null=True, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.CharField(blank=True, max_length=75, null=True, verbose_name='Email')),
                ('uscad', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Cadastro')),
                ('dtcad', models.DateTimeField(blank=True, null=True, verbose_name='Data Cadastro')),
                ('usalt', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Alteração')),
                ('dtalt', models.DateTimeField(blank=True, null=True, verbose_name='Data Alteração')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'db_table': 'UNIDADE',
            },
        ),
        migrations.RemoveField(
            model_name='permissaousuario',
            name='permissao',
        ),
        migrations.RemoveField(
            model_name='permissaousuario',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cod_unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuario.unidade', verbose_name='Unidade'),
        ),
        migrations.DeleteModel(
            name='Permissao',
        ),
        migrations.DeleteModel(
            name='PermissaoUsuario',
        ),
    ]
