# Generated by Django 6.0.1 on 2026-02-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_unidade_remove_permissaousuario_permissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
