# Generated by Django 6.0.1 on 2026-02-03 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_unidade_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unidade',
            table=None,
        ),
    ]
