# Generated by Django 6.0.1 on 2026-03-01 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_remove_historicalmedicoespecialidade_dtalt_and_more'),
        ('usuario', '0008_historicalunidade_historicalusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuario',
            name='cod_medico',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='medico.medico', verbose_name='Médico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cod_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='medico.medico', verbose_name='Médico'),
        ),
    ]
