# Generated by Django 6.0.1 on 2026-04-18 01:08

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def criar_clinica_padrao(apps, schema_editor):
    Clinica = apps.get_model('usuario', 'Clinica')
    Unidade = apps.get_model('usuario', 'Unidade')
    Usuario = apps.get_model('usuario', 'Usuario')
    HistoricalUnidade = apps.get_model('usuario', 'HistoricalUnidade')
    HistoricalUsuario = apps.get_model('usuario', 'HistoricalUsuario')

    unidade_base = Unidade.objects.order_by('id').first()
    clinica, _ = Clinica.objects.get_or_create(
        nome_fantasia=(unidade_base.descricao if unidade_base else 'Clinica Principal'),
        defaults={
            'razao_social': unidade_base.descricao if unidade_base else 'Clinica Principal',
            'cnpj': getattr(unidade_base, 'cnpj', None),
            'email': getattr(unidade_base, 'email', None),
            'telefone': getattr(unidade_base, 'telefone', None),
            'plano': 'PROFISSIONAL',
            'status': True,
            'uscad': 'migracao',
            'usalt': 'migracao',
        },
    )

    Unidade.objects.filter(clinica__isnull=True).update(clinica=clinica)
    Usuario.objects.filter(clinica__isnull=True).update(clinica=clinica)
    HistoricalUnidade.objects.filter(clinica__isnull=True).update(clinica=clinica)
    HistoricalUsuario.objects.filter(clinica__isnull=True).update(clinica=clinica)


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_alter_historicalusuario_cod_medico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunidade',
            name='clinica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='historicalusuario',
            name='clinica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.CreateModel(
            name='HistoricalClinica',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=80, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=120, null=True, verbose_name='Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('plano', models.CharField(choices=[('BASICO', 'Básico'), ('PROFISSIONAL', 'Profissional')], default='BASICO', max_length=20, verbose_name='Plano')),
                ('status', models.BooleanField(default=True, verbose_name='Ativa')),
                ('uscad', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Cadastro')),
                ('dtcad', models.DateTimeField(blank=True, editable=False, verbose_name='Data Cadastro')),
                ('usalt', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Alteração')),
                ('dtalt', models.DateTimeField(blank=True, editable=False, verbose_name='Data Alteração')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Clínica',
                'verbose_name_plural': 'historical Clínicas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RunPython(criar_clinica_padrao, migrations.RunPython.noop),
    ]
