# Generated by Django 6.0.1 on 2026-04-22 01:52

import usuario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_remove_agenda_agenda_unique_horario_medico_unidade_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('financeiro', '0004_remove_historicallancamentofinanceiro_unidade_and_more'),
        ('medico', '0006_alter_medicoagenda_options_and_more'),
        ('usuario', '0010_clinica_historicalunidade_clinica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalusuario',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='historicalusuario',
            name='cod_medico',
        ),
        migrations.RemoveField(
            model_name='historicalusuario',
            name='cod_unidade',
        ),
        migrations.RemoveField(
            model_name='historicalusuario',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cod_unidade',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cod_medico',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.AlterModelManagers(
            name='clinica',
            managers=[
                ('objects', usuario.models.ClinicaManager()),
            ],
        ),
        migrations.AddField(
            model_name='clinica',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Acesso ao Admin'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='reseta_senha',
            field=models.BooleanField(default=False, verbose_name='Forçar Redefinição de Senha'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='historicalclinica',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Acesso ao Admin'),
        ),
        migrations.AddField(
            model_name='historicalclinica',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='historicalclinica',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='historicalclinica',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='historicalclinica',
            name='reseta_senha',
            field=models.BooleanField(default=False, verbose_name='Forçar Redefinição de Senha'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='plano',
            field=models.CharField(choices=[('BASICO', 'Básico'), ('PROFISSIONAL', 'Profissional'), ('PRO', 'Pro')], default='BASICO', max_length=20, verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='historicalclinica',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='historicalclinica',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='historicalclinica',
            name='plano',
            field=models.CharField(choices=[('BASICO', 'Básico'), ('PROFISSIONAL', 'Profissional'), ('PRO', 'Pro')], default='BASICO', max_length=20, verbose_name='Plano'),
        ),
        migrations.DeleteModel(
            name='HistoricalUnidade',
        ),
        migrations.DeleteModel(
            name='HistoricalUsuario',
        ),
        migrations.DeleteModel(
            name='Unidade',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
