# Generated by Django 6.0.1 on 2026-04-25 15:20

import django.db.models.deletion
import simple_history.models
import usuario.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuario', '0012_rename_pro_to_enterprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('password', models.CharField(default='', max_length=128, verbose_name='password')),
                ('papel', models.CharField(choices=[('ADMIN', 'Administrador'), ('RECEPCAO', 'Recepção'), ('FINANCEIRO', 'Financeiro'), ('ENFERMAGEM', 'Enfermagem'), ('MEDICO', 'Médico')], default='RECEPCAO', max_length=20, verbose_name='Papel')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acesso ao Admin')),
                ('reseta_senha', models.BooleanField(default=False, verbose_name='Forçar Redefinição de Senha')),
                ('uscad', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Cadastro')),
                ('dtcad', models.DateTimeField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('usalt', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Alteração')),
                ('dtalt', models.DateTimeField(auto_now=True, verbose_name='Data Alteração')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to=settings.AUTH_USER_MODEL, verbose_name='Clínica')),
                ('groups', models.ManyToManyField(blank=True, related_name='colaborador_set', related_query_name='colaborador', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='colaborador_set', related_query_name='colaborador', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome'],
            },
            managers=[
                ('objects', usuario.models.ColaboradorManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalColaborador',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('email', models.EmailField(db_index=True, max_length=100, verbose_name='Email')),
                ('password', models.CharField(default='', max_length=128, verbose_name='password')),
                ('papel', models.CharField(choices=[('ADMIN', 'Administrador'), ('RECEPCAO', 'Recepção'), ('FINANCEIRO', 'Financeiro'), ('ENFERMAGEM', 'Enfermagem'), ('MEDICO', 'Médico')], default='RECEPCAO', max_length=20, verbose_name='Papel')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acesso ao Admin')),
                ('reseta_senha', models.BooleanField(default=False, verbose_name='Forçar Redefinição de Senha')),
                ('uscad', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Cadastro')),
                ('dtcad', models.DateTimeField(blank=True, editable=False, verbose_name='Data Cadastro')),
                ('usalt', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Alteração')),
                ('dtalt', models.DateTimeField(blank=True, editable=False, verbose_name='Data Alteração')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('clinica', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Clínica')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Colaborador',
                'verbose_name_plural': 'historical Colaboradores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
