# Generated by Django 6.0.1 on 2026-04-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_colaborador_historicalcolaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='modulos_permitidos',
            field=models.JSONField(blank=True, default=list, verbose_name='Módulos permitidos'),
        ),
        migrations.AddField(
            model_name='historicalcolaborador',
            name='modulos_permitidos',
            field=models.JSONField(blank=True, default=list, verbose_name='Módulos permitidos'),
        ),
    ]
