# Generated by Django 6.0.1 on 2026-02-18 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('paciente', '0006_alter_historicalpaciente_convenio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Convenio',
        ),
        migrations.DeleteModel(
            name='HistoricalConvenio',
        ),
    ]
