# Generated by Django 6.0.1 on 2026-04-18 18:34

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def criar_categorias_padrao(apps, schema_editor):
    Clinica = apps.get_model("usuario", "Clinica")
    CategoriaFinanceira = apps.get_model("financeiro", "CategoriaFinanceira")

    categorias = [
        ("RECEITA", "Consultas", "badge-primary"),
        ("RECEITA", "Procedimentos", "badge-info"),
        ("RECEITA", "Vacinas", "badge-success"),
        ("RECEITA", "Exames", "badge-accent"),
        ("RECEITA", "Receitas Diversas", "badge-secondary"),
        ("DESPESA", "Folha e Prestadores", "badge-warning"),
        ("DESPESA", "Infraestrutura", "badge-error"),
        ("DESPESA", "Materiais e Insumos", "badge-neutral"),
        ("DESPESA", "Marketing", "badge-secondary"),
        ("DESPESA", "Despesas Diversas", "badge-ghost"),
    ]

    for clinica in Clinica.objects.all():
        for tipo, descricao, cor in categorias:
            CategoriaFinanceira.objects.get_or_create(
                clinica=clinica,
                tipo=tipo,
                descricao=descricao,
                defaults={
                    "cor": cor,
                    "status": True,
                    "uscad": "migracao",
                    "usalt": "migracao",
                },
            )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0005_convenio_clinica_especialidade_clinica_and_more'),
        ('financeiro', '0002_delete_convenio_delete_historicalconvenio'),
        ('paciente', '0009_historicalpaciente_clinica_and_more'),
        ('usuario', '0010_clinica_historicalunidade_clinica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], default='RECEITA', max_length=10, verbose_name='Tipo')),
                ('cor', models.CharField(default='badge-primary', max_length=20, verbose_name='Cor')),
                ('status', models.BooleanField(default=True, verbose_name='Ativa')),
                ('uscad', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Cadastro')),
                ('dtcad', models.DateTimeField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('usalt', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Alteração')),
                ('dtalt', models.DateTimeField(auto_now=True, verbose_name='Data Alteração')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_financeiras', to='usuario.clinica', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
                'ordering': ['tipo', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCategoriaFinanceira',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], default='RECEITA', max_length=10, verbose_name='Tipo')),
                ('cor', models.CharField(default='badge-primary', max_length=20, verbose_name='Cor')),
                ('status', models.BooleanField(default=True, verbose_name='Ativa')),
                ('uscad', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Cadastro')),
                ('dtcad', models.DateTimeField(blank=True, editable=False, verbose_name='Data Cadastro')),
                ('usalt', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Alteração')),
                ('dtalt', models.DateTimeField(blank=True, editable=False, verbose_name='Data Alteração')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('clinica', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.clinica', verbose_name='Clínica')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Categoria Financeira',
                'verbose_name_plural': 'historical Categorias Financeiras',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLancamentoFinanceiro',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], default='RECEITA', max_length=10, verbose_name='Tipo')),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual'), ('VACINA', 'Vacina'), ('PROCEDIMENTO', 'Procedimento'), ('CONSULTA', 'Consulta'), ('OUTRO', 'Outro')], default='MANUAL', max_length=20, verbose_name='Origem')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado'), ('PARCIAL', 'Parcial')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('descricao', models.CharField(max_length=120, verbose_name='Descrição')),
                ('nome_cliente', models.CharField(blank=True, max_length=80, null=True, verbose_name='Cliente')),
                ('data_lancamento', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do Lançamento')),
                ('competencia', models.DateField(default=django.utils.timezone.localdate, verbose_name='Competência')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Recebido/Pago')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('uscad', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Cadastro')),
                ('dtcad', models.DateTimeField(blank=True, editable=False, verbose_name='Data Cadastro')),
                ('usalt', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Alteração')),
                ('dtalt', models.DateTimeField(blank=True, editable=False, verbose_name='Data Alteração')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.categoriafinanceira', verbose_name='Categoria')),
                ('clinica', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.clinica', verbose_name='Clínica')),
                ('convenio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.convenio', verbose_name='Convênio')),
                ('forma_pagamento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.formapagamento', verbose_name='Forma de Pagamento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='paciente.paciente', verbose_name='Paciente')),
                ('unidade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.unidade', verbose_name='Unidade')),
                ('vacina', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='paciente.pacientevacina', verbose_name='Vacina')),
            ],
            options={
                'verbose_name': 'historical Lançamento Financeiro',
                'verbose_name_plural': 'historical Lançamentos Financeiros',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], default='RECEITA', max_length=10, verbose_name='Tipo')),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual'), ('VACINA', 'Vacina'), ('PROCEDIMENTO', 'Procedimento'), ('CONSULTA', 'Consulta'), ('OUTRO', 'Outro')], default='MANUAL', max_length=20, verbose_name='Origem')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado'), ('PARCIAL', 'Parcial')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('descricao', models.CharField(max_length=120, verbose_name='Descrição')),
                ('nome_cliente', models.CharField(blank=True, max_length=80, null=True, verbose_name='Cliente')),
                ('data_lancamento', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do Lançamento')),
                ('competencia', models.DateField(default=django.utils.timezone.localdate, verbose_name='Competência')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Recebido/Pago')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('uscad', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Cadastro')),
                ('dtcad', models.DateTimeField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('usalt', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuário Alteração')),
                ('dtalt', models.DateTimeField(auto_now=True, verbose_name='Data Alteração')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.categoriafinanceira', verbose_name='Categoria')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='usuario.clinica', verbose_name='Clínica')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_financeiros', to='base.convenio', verbose_name='Convênio')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_financeiros', to='base.formapagamento', verbose_name='Forma de Pagamento')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_financeiros', to='paciente.paciente', verbose_name='Paciente')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='usuario.unidade', verbose_name='Unidade')),
                ('vacina', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamento_financeiro', to='paciente.pacientevacina', verbose_name='Vacina')),
            ],
            options={
                'verbose_name': 'Lançamento Financeiro',
                'verbose_name_plural': 'Lançamentos Financeiros',
                'ordering': ['-data_vencimento', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoriafinanceira',
            constraint=models.UniqueConstraint(fields=('clinica', 'tipo', 'descricao'), name='financeiro_categoria_unique_por_clinica'),
        ),
        migrations.RunPython(criar_categorias_padrao, migrations.RunPython.noop),
    ]
