# Generated by Django 6.0.1 on 2026-04-22 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallancamentofinanceiro',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='lancamentofinanceiro',
            name='unidade',
        ),
    ]
