# Generated by Codex on 2026-04-22

from django.db import migrations


def corrigir_fk_historico_categoria(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return

    with schema_editor.connection.cursor() as cursor:
        fks = cursor.execute(
            "PRAGMA foreign_key_list(financeiro_historicalcategoriafinanceira)"
        ).fetchall()
        if not any(fk[2] == "usuario_usuario" for fk in fks):
            return

        cursor.execute("PRAGMA foreign_keys=OFF")
        cursor.execute(
            """
            CREATE TABLE financeiro_historicalcategoriafinanceira_new (
                id bigint NOT NULL,
                descricao varchar(80) NOT NULL,
                tipo varchar(10) NOT NULL,
                cor varchar(20) NOT NULL,
                status bool NOT NULL,
                uscad varchar(25) NULL,
                dtcad datetime NOT NULL,
                usalt varchar(25) NULL,
                dtalt datetime NOT NULL,
                history_id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                history_date datetime NOT NULL,
                history_change_reason varchar(100) NULL,
                history_type varchar(1) NOT NULL,
                clinica_id bigint NULL REFERENCES usuario_clinica (id) DEFERRABLE INITIALLY DEFERRED,
                history_user_id bigint NULL REFERENCES usuario_clinica (id) DEFERRABLE INITIALLY DEFERRED
            )
            """
        )
        cursor.execute(
            """
            INSERT INTO financeiro_historicalcategoriafinanceira_new (
                id, descricao, tipo, cor, status, uscad, dtcad, usalt, dtalt,
                history_id, history_date, history_change_reason, history_type,
                clinica_id, history_user_id
            )
            SELECT
                id, descricao, tipo, cor, status, uscad, dtcad, usalt, dtalt,
                history_id, history_date, history_change_reason, history_type,
                clinica_id, history_user_id
            FROM financeiro_historicalcategoriafinanceira
            """
        )
        cursor.execute("DROP TABLE financeiro_historicalcategoriafinanceira")
        cursor.execute(
            """
            ALTER TABLE financeiro_historicalcategoriafinanceira_new
            RENAME TO financeiro_historicalcategoriafinanceira
            """
        )
        cursor.execute(
            """
            CREATE INDEX financeiro_historicalcategoriafinanceira_history_user_id_cac6ea79
            ON financeiro_historicalcategoriafinanceira (history_user_id)
            """
        )
        cursor.execute(
            """
            CREATE INDEX financeiro_historicalcategoriafinanceira_clinica_id_9826bd41
            ON financeiro_historicalcategoriafinanceira (clinica_id)
            """
        )
        cursor.execute(
            """
            CREATE INDEX financeiro_historicalcategoriafinanceira_history_date_dc10c595
            ON financeiro_historicalcategoriafinanceira (history_date)
            """
        )
        cursor.execute(
            """
            CREATE INDEX financeiro_historicalcategoriafinanceira_id_45de43a1
            ON financeiro_historicalcategoriafinanceira (id)
            """
        )
        cursor.execute("PRAGMA foreign_keys=ON")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("financeiro", "0005_alter_historicalcategoriafinanceira_history_user"),
    ]

    operations = [
        migrations.RunPython(
            corrigir_fk_historico_categoria,
            migrations.RunPython.noop,
        ),
    ]
