# Generated by Django 6.0.1 on 2026-04-18 01:08

import django.db.models.deletion
from django.db import migrations, models


def vincular_registros_base_a_clinica(apps, schema_editor):
    Clinica = apps.get_model('usuario', 'Clinica')
    clinica = Clinica.objects.order_by('id').first()
    if not clinica:
        return

    modelos = [
        ('base', 'Convenio'),
        ('base', 'Especialidade'),
        ('base', 'FormaPagamento'),
        ('base', 'TipoConsulta'),
        ('base', 'TipoExame'),
        ('base', 'TipoMaterial'),
        ('base', 'StatusAgendamento'),
        ('base', 'StatusAutorizacao'),
        ('base', 'StatusProcedimento'),
        ('base', 'HistoricalConvenio'),
        ('base', 'HistoricalEspecialidade'),
        ('base', 'HistoricalFormaPagamento'),
        ('base', 'HistoricalStatusAgendamento'),
        ('base', 'HistoricalStatusAutorizacao'),
        ('base', 'HistoricalStatusProcedimento'),
        ('base', 'HistoricalTipoConsulta'),
        ('base', 'HistoricalTipoExame'),
        ('base', 'HistoricalTipoMaterial'),
    ]
    for app_label, model_name in modelos:
        apps.get_model(app_label, model_name).objects.filter(clinica__isnull=True).update(clinica=clinica)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_statusagendamento_statusautorizacao_and_more'),
        ('usuario', '0010_clinica_historicalunidade_clinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convenios', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='especialidade',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='especialidades', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formas_pagamento', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='historicalconvenio',
            name='clinica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='historicalespecialidade',
            name='clinica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='historicalformapagamento',
            name='clinica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='historicalstatusagendamento',
            name='clinica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='historicalstatusautorizacao',
            name='clinica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='historicalstatusprocedimento',
            name='clinica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='historicaltipoconsulta',
            name='clinica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='historicaltipoexame',
            name='clinica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='historicaltipomaterial',
            name='clinica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='statusagendamento',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_agendamento', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='statusautorizacao',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_autorizacao', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='statusprocedimento',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_procedimento', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='tipoconsulta',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipos_consulta', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='tipoexame',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipos_exame', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='tipomaterial',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipos_materiais', to='usuario.clinica', verbose_name='Clínica'),
        ),
        migrations.RunPython(vincular_registros_base_a_clinica, migrations.RunPython.noop),
    ]
