# Generated by Codex on 2026-04-22

from django.db import migrations


DEFAULT_STATUS_AGENDAMENTO = (
    {"descricao": "Agendado", "cor": "btn-primary", "nivel": 1},
    {"descricao": "Em Andamento", "cor": "btn-warning", "nivel": 2},
    {"descricao": "Finalizado", "cor": "btn-success", "nivel": 2},
    {"descricao": "Faltou", "cor": "btn-neutral", "nivel": 2},
    {"descricao": "Cancelado", "cor": "btn-error", "nivel": 2},
)


def seed_default_status_agendamento(apps, schema_editor):
    Clinica = apps.get_model("usuario", "Clinica")
    StatusAgendamento = apps.get_model("base", "StatusAgendamento")

    for clinica in Clinica.objects.all():
        for item in DEFAULT_STATUS_AGENDAMENTO:
            StatusAgendamento.objects.get_or_create(
                clinica=clinica,
                descricao=item["descricao"],
                defaults={
                    "cor": item["cor"],
                    "nivel": item["nivel"],
                    "status": True,
                    "uscad": "migracao",
                    "usalt": "migracao",
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_convenio_clinica_especialidade_clinica_and_more"),
        ("usuario", "0011_remove_historicalusuario_clinica_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_default_status_agendamento, migrations.RunPython.noop),
    ]
